[0m20:40:03.244916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110221fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a2f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a2fc50>]}


============================== 20:40:03.264430 | 4915f5cf-2b75-4755-a70c-1e555f7d2927 ==============================
[0m20:40:03.264430 [info ] [MainThread]: Running with dbt=1.9.3
[0m20:40:03.264754 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/namtonthat/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init api-health-data', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:40:03.298526 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/namtonthat/.dbt')}
[0m20:40:03.298801 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:40:15.186870 [debug] [MainThread]: Starter project path: /Users/namtonthat/github/apple-health-calendar/.venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m20:40:15.195228 [info ] [MainThread]: 
Your new dbt project "api_health_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:40:15.195659 [info ] [MainThread]: Setting up your profile.
[0m20:40:15.196341 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m20:40:15.200092 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 11.990259, "process_in_blocks": "0", "process_kernel_time": 0.299608, "process_mem_max_rss": "127369216", "process_out_blocks": "0", "process_user_time": 1.467697}
[0m20:40:15.200656 [debug] [MainThread]: Command `dbt init` failed at 20:40:15.200538 after 11.99 seconds
[0m20:40:15.201111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112a8ac40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112ac5b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11289b020>]}
[0m20:40:15.201523 [debug] [MainThread]: Flushing usage events
[0m20:40:16.316926 [debug] [MainThread]: An error was encountered while trying to flush usage events
